//! Helper macros and utilities for atomic operations
//! Auto-generated by batch fix script

/// Load from atomic with Relaxed ordering
#[inline]
pub fn atomic_load_u32(atomic: &core::sync::atomic::AtomicU32) -> u32 {
    atomic.load(core::sync::atomic::Ordering::Relaxed)
}

/// Store to atomic with Relaxed ordering
#[inline]
pub fn atomic_store_u32(atomic: &core::sync::atomic::AtomicU32, val: u32) {
    atomic.store(val, core::sync::atomic::Ordering::Relaxed);
}

/// Fetch and add
#[inline]
pub fn atomic_fetch_add_u32(atomic: &core::sync::atomic::AtomicU32, val: u32) -> u32 {
    atomic.fetch_add(val, core::sync::atomic::Ordering::Relaxed)
}

/// Similar helpers for u64, usize, bool, and pointers
#[inline]
pub fn atomic_load_u64(atomic: &core::sync::atomic::AtomicU64) -> u64 {
    atomic.load(core::sync::atomic::Ordering::Relaxed)
}

#[inline]
pub fn atomic_store_u64(atomic: &core::sync::atomic::AtomicU64, val: u64) {
    atomic.store(val, core::sync::atomic::Ordering::Relaxed);
}

#[inline]
pub fn atomic_load_bool(atomic: &core::sync::atomic::AtomicBool) -> bool {
    atomic.load(core::sync::atomic::Ordering::Relaxed)
}

#[inline]
pub fn atomic_store_bool(atomic: &core::sync::atomic::AtomicBool, val: bool) {
    atomic.store(val, core::sync::atomic::Ordering::Relaxed);
}

#[inline]
pub fn atomic_load_ptr<T>(atomic: &core::sync::atomic::AtomicPtr<T>) -> *mut T {
    atomic.load(core::sync::atomic::Ordering::Relaxed)
}

#[inline]
pub fn atomic_store_ptr<T>(atomic: &core::sync::atomic::AtomicPtr<T>, val: *mut T) {
    atomic.store(val, core::sync::atomic::Ordering::Relaxed);
}
