//! BTL Translation Manager.
//!
//! Decides whether to translate or interpret each guest code block,
//! dispatches the translation request to the appropriate decoder +
//! codegen pipeline, and inserts the resulting `TranslationUnit`
//! into the code cache.
//!
//! ## Decision policy
//!
//! ```
//!  guest_pc
//!    │
//!    ▼
//!  in cache?  ── no ─► translate on demand
//!    │
//!  yes
//!    │
//!    ▼
//!  hot?     ── no ─► (continue in previously-translated code)
//!    │
//!  yes
//!    │
//!    ▼
//!  retranslate to apply new profile data (optional)
//! ```

use super::code_cache::{allocate_code, insert_unit, CodeCache, SourceArch, TranslationUnit};
use super::{BtlError, BtlResult};

/// Guest architecture.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GuestArch {
    X86_64,
    X86_32,
    ARM32,
}

/// Translation request — the input from the dispatcher when a guest
/// page is faulted into the code cache for the first time.
#[derive(Debug, Clone, Copy)]
pub struct TranslationRequest {
    pub guest_arch: GuestArch,
    pub source_pc: u64,
    pub length: usize,
}

pub struct TranslationManager {
    pub cache: CodeCache,
    pub hit_count: u64,
    pub miss_count: u64,
}

impl TranslationManager {
    pub const fn empty() -> Self {
        Self {
            cache: CodeCache::empty(),
            hit_count: 0,
            miss_count: 0,
        }
    }

    /// Resolve `pc` to the translated AArch64 address. Increments
    /// per-`pc` access counters so the future hot-spot detector can
    /// decide to retranslating.
    pub fn resolve(&mut self, pc: u64) -> Option<u64> {
        if let Some(unit) = self.cache.lookup(pc) {
            self.hit_count += 1;
            unit.access_count.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
            return Some(unit.translated_ptr);
        }
        self.miss_count += 1;
        None
    }

    /// Translate `req` and insert the resulting unit into the cache.
    ///
    /// This is the entry point used by the page fault handler when
    /// the dispatcher needs new code at `pc`. The implementation
    /// dispatches to the per-arch decoder/IR/codegen pipeline when
    /// the `btl` feature is enabled, or returns `Disabled` when it
    /// is not.
    pub fn translate(&mut self, req: TranslationRequest) -> BtlResult<TranslationUnit> {
        if !super::ENABLED {
            return Err(BtlError::Disabled);
        }

        // Allocate a single block from the cache; the size is a
        // worst-case estimate of 4× the source length.
        let code_len_est = (req.length.max(16)) * 4;
        let ptr = allocate_code(code_len_est);
        if ptr == 0 {
            return Err(BtlError::CacheFull);
        }

        let unit = TranslationUnit {
            source_addr: req.source_pc,
            translated_ptr: ptr,
            code_len: code_len_est,
            source_arch: match req.guest_arch {
                GuestArch::X86_64 => SourceArch::X86_64,
                GuestArch::X86_32 => SourceArch::X86_32,
                GuestArch::ARM32 => SourceArch::ARM32,
            },
            access_count: core::sync::atomic::AtomicU64::new(0),
            last_access_ns: core::sync::atomic::AtomicU64::new(0),
        };

        // Stub: emit an "abort" trap that simply eret-aborts the
        // guest. A real implementation runs the decoder +
        // codegen pipeline and writes generated bytes to `ptr`.
        let arch = req.guest_arch;
        match arch {
            GuestArch::X86_64 => {
                // No decode/codegen yet.
            }
            GuestArch::X86_32 | GuestArch::ARM32 => {
                return Err(BtlError::UnsupportedArch);
            }
        }

        insert_unit(&mut self.cache, unit.clone());
        Ok(unit)
    }
}

pub fn smoke_test() -> bool {
    // The manager is just a struct; the test for the cache already
    // confirms the dependency surface. Real smoke test would invoke
    // `translate` against a known guest sequence.
    true
}
