//! Interrupt Descriptor Table (IDT)
//
//! 256-entry IDT for the x86_64 exception and interrupt vectors.
//! The first 32 are CPU-defined exceptions; the rest are user-
//! defined IRQ handlers, dispatched through the APIC or the legacy
//! 8259 PIC.
//
//! Each entry uses the `GateDescriptor` format (16 bytes): handler
//! address, segment selector (always `KERNEL_CS`), IST field, type
//! and DPL, plus the upper 32 bits of the handler address.

use core::arch::asm;

#[repr(C, packed)]
#[derive(Clone, Copy, Default)]
pub struct GateDescriptor {
    pub offset_low: u16,
    pub selector: u16,
    pub ist: u8,
    pub type_attr: u8,
    pub offset_mid: u16,
    pub offset_high: u32,
    pub _reserved: u32,
}

impl GateDescriptor {
    pub const fn empty() -> Self {
        Self { offset_low: 0, selector: 0, ist: 0, type_attr: 0,
               offset_mid: 0, offset_high: 0, _reserved: 0 }
    }
    /// Build a 64-bit interrupt gate.
    pub fn interrupt(handler: u64, sel: u16, ist: u8, dpl: u8) -> Self {
        Self {
            offset_low: (handler & 0xFFFF) as u16,
            selector: sel,
            ist: ist & 0x7,
            type_attr: 0x8E | ((dpl & 0x3) << 5),
            offset_mid: ((handler >> 16) & 0xFFFF) as u16,
            offset_high: ((handler >> 32) & 0xFFFF_FFFF) as u32,
            _reserved: 0,
        }
    }
}

#[repr(C, packed)]
struct IdtPtr {
    limit: u16,
    base: u64,
}

static mut IDT: [GateDescriptor; 256] = [const { GateDescriptor::empty() }; 256];

extern "C" {
    // The exception handler entry points are generated by the
    // `idt_stubs` global_asm! block. The dispatcher is
    // `int_common_dispatch` in `idt_stubs.rs`.
    fn int_stub_0();
    fn int_stub_1();
    fn int_stub_2();
    fn int_stub_3();
    fn int_stub_4();
    fn int_stub_5();
    fn int_stub_6();
    fn int_stub_7();
    fn int_stub_8();
    fn int_stub_9();
    fn int_stub_10();
    fn int_stub_11();
    fn int_stub_12();
    fn int_stub_13();
    fn int_stub_14();
    fn int_stub_15();
    fn int_stub_16();
    fn int_stub_17();
    fn int_stub_18();
    fn int_stub_19();
    fn int_stub_20();
    fn int_stub_21();
    fn int_stub_22();
    fn int_stub_23();
    fn int_stub_24();
    fn int_stub_25();
    fn int_stub_26();
    fn int_stub_27();
    fn int_stub_28();
    fn int_stub_29();
    fn int_stub_30();
    fn int_stub_31();
    // Hardware IRQ stubs (vectors 32-255)
    fn int_stub_32();
    fn int_stub_33();
    fn int_stub_34();
    fn int_stub_35();
    fn int_stub_36();
    fn int_stub_37();
    fn int_stub_38();
    fn int_stub_39();
    fn int_stub_40();
    fn int_stub_41();
    fn int_stub_42();
    fn int_stub_43();
    fn int_stub_44();
    fn int_stub_45();
    fn int_stub_46();
    fn int_stub_47();
    fn int_stub_48();
    fn int_stub_49();
    fn int_stub_50();
    fn int_stub_51();
    fn int_stub_52();
    fn int_stub_53();
    fn int_stub_54();
    fn int_stub_55();
    fn int_stub_56();
    fn int_stub_57();
    fn int_stub_58();
    fn int_stub_59();
    fn int_stub_60();
    fn int_stub_61();
    fn int_stub_62();
    fn int_stub_63();
    fn int_stub_64();
    fn int_stub_65();
    fn int_stub_66();
    fn int_stub_67();
    fn int_stub_68();
    fn int_stub_69();
    fn int_stub_70();
    fn int_stub_71();
    fn int_stub_72();
    fn int_stub_73();
    fn int_stub_74();
    fn int_stub_75();
    fn int_stub_76();
    fn int_stub_77();
    fn int_stub_78();
    fn int_stub_79();
    fn int_stub_80();
    fn int_stub_81();
    fn int_stub_82();
    fn int_stub_83();
    fn int_stub_84();
    fn int_stub_85();
    fn int_stub_86();
    fn int_stub_87();
    fn int_stub_88();
    fn int_stub_89();
    fn int_stub_90();
    fn int_stub_91();
    fn int_stub_92();
    fn int_stub_93();
    fn int_stub_94();
    fn int_stub_95();
    fn int_stub_96();
    fn int_stub_97();
    fn int_stub_98();
    fn int_stub_99();
    fn int_stub_100();
    fn int_stub_101();
    fn int_stub_102();
    fn int_stub_103();
    fn int_stub_104();
    fn int_stub_105();
    fn int_stub_106();
    fn int_stub_107();
    fn int_stub_108();
    fn int_stub_109();
    fn int_stub_110();
    fn int_stub_111();
    fn int_stub_112();
    fn int_stub_113();
    fn int_stub_114();
    fn int_stub_115();
    fn int_stub_116();
    fn int_stub_117();
    fn int_stub_118();
    fn int_stub_119();
    fn int_stub_120();
    fn int_stub_121();
    fn int_stub_122();
    fn int_stub_123();
    fn int_stub_124();
    fn int_stub_125();
    fn int_stub_126();
    fn int_stub_127();
    fn int_stub_128();
    fn int_stub_129();
    fn int_stub_130();
    fn int_stub_131();
    fn int_stub_132();
    fn int_stub_133();
    fn int_stub_134();
    fn int_stub_135();
    fn int_stub_136();
    fn int_stub_137();
    fn int_stub_138();
    fn int_stub_139();
    fn int_stub_140();
    fn int_stub_141();
    fn int_stub_142();
    fn int_stub_143();
    fn int_stub_144();
    fn int_stub_145();
    fn int_stub_146();
    fn int_stub_147();
    fn int_stub_148();
    fn int_stub_149();
    fn int_stub_150();
    fn int_stub_151();
    fn int_stub_152();
    fn int_stub_153();
    fn int_stub_154();
    fn int_stub_155();
    fn int_stub_156();
    fn int_stub_157();
    fn int_stub_158();
    fn int_stub_159();
    fn int_stub_160();
    fn int_stub_161();
    fn int_stub_162();
    fn int_stub_163();
    fn int_stub_164();
    fn int_stub_165();
    fn int_stub_166();
    fn int_stub_167();
    fn int_stub_168();
    fn int_stub_169();
    fn int_stub_170();
    fn int_stub_171();
    fn int_stub_172();
    fn int_stub_173();
    fn int_stub_174();
    fn int_stub_175();
    fn int_stub_176();
    fn int_stub_177();
    fn int_stub_178();
    fn int_stub_179();
    fn int_stub_180();
    fn int_stub_181();
    fn int_stub_182();
    fn int_stub_183();
    fn int_stub_184();
    fn int_stub_185();
    fn int_stub_186();
    fn int_stub_187();
    fn int_stub_188();
    fn int_stub_189();
    fn int_stub_190();
    fn int_stub_191();
    fn int_stub_192();
    fn int_stub_193();
    fn int_stub_194();
    fn int_stub_195();
    fn int_stub_196();
    fn int_stub_197();
    fn int_stub_198();
    fn int_stub_199();
    fn int_stub_200();
    fn int_stub_201();
    fn int_stub_202();
    fn int_stub_203();
    fn int_stub_204();
    fn int_stub_205();
    fn int_stub_206();
    fn int_stub_207();
    fn int_stub_208();
    fn int_stub_209();
    fn int_stub_210();
    fn int_stub_211();
    fn int_stub_212();
    fn int_stub_213();
    fn int_stub_214();
    fn int_stub_215();
    fn int_stub_216();
    fn int_stub_217();
    fn int_stub_218();
    fn int_stub_219();
    fn int_stub_220();
    fn int_stub_221();
    fn int_stub_222();
    fn int_stub_223();
    fn int_stub_224();
    fn int_stub_225();
    fn int_stub_226();
    fn int_stub_227();
    fn int_stub_228();
    fn int_stub_229();
    fn int_stub_230();
    fn int_stub_231();
    fn int_stub_232();
    fn int_stub_233();
    fn int_stub_234();
    fn int_stub_235();
    fn int_stub_236();
    fn int_stub_237();
    fn int_stub_238();
    fn int_stub_239();
    fn int_stub_240();
    fn int_stub_241();
    fn int_stub_242();
    fn int_stub_243();
    fn int_stub_244();
    fn int_stub_245();
    fn int_stub_246();
    fn int_stub_247();
    fn int_stub_248();
    fn int_stub_249();
    fn int_stub_250();
    fn int_stub_251();
    fn int_stub_252();
    fn int_stub_253();
    fn int_stub_254();
    fn int_stub_255();
}

/// Set the gate for `vector` to the supplied handler.
/// Uses selector 0x38 (OVMF slot 7 — the 64-bit kernel CS). Slot 2
/// (0x10) is only the legacy 32-bit code segment and is **invalid**
/// as a target CS for an interrupt gate in long mode (the CPU faults
/// during delivery).
pub fn set_gate(vector: u8, handler: u64, ist: u8, dpl: u8) {
    unsafe {
        let entry = &mut IDT[vector as usize];
        *entry = GateDescriptor::interrupt(handler, crate::arch::x86_64::gdt::KERNEL_CS, ist, dpl);
    }
}

/// Install the IDT and fill hardware IRQ vectors (32-255).
pub fn init() {
    // Pre-fault all pages that the IDT spans (256 entries × 16 bytes = 4096 bytes = 1 page).
    // If any page is not yet mapped in the temporary UEFI page table, this will fault while
    // the IDT pointer is still set to a temporary identity-mapped address. Do this before
    // setting idt_ptr to avoid double-faulting.
    // SAFETY: IDT is a static mutable, and we are in init() which runs before any other
    // CPU can touch it. Reading bytes just to fault the page in is safe.
    unsafe {
        let idt_base = &IDT as *const GateDescriptor;
        let idt_page_start = idt_base as u64;
        let idt_page_end = idt_page_start + core::mem::size_of_val(&IDT) as u64;
        // Touch the first byte of each 4 KiB page that IDT spans.
        let mut page = idt_page_start;
        while page < idt_page_end {
            core::ptr::read_volatile(page as *const u8);
            page += 4096;
        }
    }

    // Wire up vectors 0..32 to the assembly stubs.
    unsafe {
        let stubs: [unsafe extern "C" fn(); 32] = [
            int_stub_0, int_stub_1, int_stub_2, int_stub_3, int_stub_4,
            int_stub_5, int_stub_6, int_stub_7, int_stub_8, int_stub_9,
            int_stub_10, int_stub_11, int_stub_12, int_stub_13, int_stub_14,
            int_stub_15, int_stub_16, int_stub_17, int_stub_18, int_stub_19,
            int_stub_20, int_stub_21, int_stub_22, int_stub_23, int_stub_24,
            int_stub_25, int_stub_26, int_stub_27, int_stub_28, int_stub_29,
            int_stub_30, int_stub_31,
        ];
        for (i, f) in stubs.iter().enumerate() {
            // Pick IST for the high-importance ones.
            let ist: u8 = match i {
                2 => 2, // NMI -> IST2
                8 => 3, // #DF -> IST3
                18 => 4, // #MC -> IST4
                _ => 0,
            };
            // The kernel CS selector is 0x38 in the OVMF GDT (slot 7,
            // the actual 64-bit kernel CS descriptor installed by
            // UEFI). Slot 2 (0x10) is only the legacy 32-bit CS and
            // would #GP during exception delivery.
            IDT[i] = GateDescriptor::interrupt(*f as u64, crate::arch::x86_64::gdt::KERNEL_CS, ist, 0);
        }

        // Wire up hardware IRQ vectors (32-255) to the interrupt stubs.
        // These will be used by PIC/APIC for ISA devices and other hardware.
        // Common ISA IRQs:
        //   IRQ 0  -> Vector 32 (PIT Timer)
        //   IRQ 1  -> Vector 33 (Keyboard)
        //   IRQ 2  -> Vector 34 (Cascade from PIC2)
        //   IRQ 3  -> Vector 35 (COM2/COM4)
        //   IRQ 4  -> Vector 36 (COM1/COM3)
        //   IRQ 5  -> Vector 37 (LPT2 / Sound)
        //   IRQ 6  -> Vector 38 (Floppy)
        //   IRQ 7  -> Vector 39 (Parallel Port)
        //   IRQ 8  -> Vector 40 (RTC)
        //   IRQ 9  -> Vector 41 (PCI/ACPI)
        //   IRQ 10 -> Vector 42 (PCI)
        //   IRQ 11 -> Vector 43 (PCI/Sound)
        //   IRQ 12 -> Vector 44 (PS/2 Mouse)
        //   IRQ 13 -> Vector 45 (Coprocessor)
        //   IRQ 14 -> Vector 46 (Primary IDE)
        //   IRQ 15 -> Vector 47 (Secondary IDE)
        let irq_stubs: [unsafe extern "C" fn(); 224] = [
            int_stub_32, int_stub_33, int_stub_34, int_stub_35,
            int_stub_36, int_stub_37, int_stub_38, int_stub_39,
            int_stub_40, int_stub_41, int_stub_42, int_stub_43,
            int_stub_44, int_stub_45, int_stub_46, int_stub_47,
            int_stub_48, int_stub_49, int_stub_50, int_stub_51,
            int_stub_52, int_stub_53, int_stub_54, int_stub_55,
            int_stub_56, int_stub_57, int_stub_58, int_stub_59,
            int_stub_60, int_stub_61, int_stub_62, int_stub_63,
            int_stub_64, int_stub_65, int_stub_66, int_stub_67,
            int_stub_68, int_stub_69, int_stub_70, int_stub_71,
            int_stub_72, int_stub_73, int_stub_74, int_stub_75,
            int_stub_76, int_stub_77, int_stub_78, int_stub_79,
            int_stub_80, int_stub_81, int_stub_82, int_stub_83,
            int_stub_84, int_stub_85, int_stub_86, int_stub_87,
            int_stub_88, int_stub_89, int_stub_90, int_stub_91,
            int_stub_92, int_stub_93, int_stub_94, int_stub_95,
            int_stub_96, int_stub_97, int_stub_98, int_stub_99,
            int_stub_100, int_stub_101, int_stub_102, int_stub_103,
            int_stub_104, int_stub_105, int_stub_106, int_stub_107,
            int_stub_108, int_stub_109, int_stub_110, int_stub_111,
            int_stub_112, int_stub_113, int_stub_114, int_stub_115,
            int_stub_116, int_stub_117, int_stub_118, int_stub_119,
            int_stub_120, int_stub_121, int_stub_122, int_stub_123,
            int_stub_124, int_stub_125, int_stub_126, int_stub_127,
            int_stub_128, int_stub_129, int_stub_130, int_stub_131,
            int_stub_132, int_stub_133, int_stub_134, int_stub_135,
            int_stub_136, int_stub_137, int_stub_138, int_stub_139,
            int_stub_140, int_stub_141, int_stub_142, int_stub_143,
            int_stub_144, int_stub_145, int_stub_146, int_stub_147,
            int_stub_148, int_stub_149, int_stub_150, int_stub_151,
            int_stub_152, int_stub_153, int_stub_154, int_stub_155,
            int_stub_156, int_stub_157, int_stub_158, int_stub_159,
            int_stub_160, int_stub_161, int_stub_162, int_stub_163,
            int_stub_164, int_stub_165, int_stub_166, int_stub_167,
            int_stub_168, int_stub_169, int_stub_170, int_stub_171,
            int_stub_172, int_stub_173, int_stub_174, int_stub_175,
            int_stub_176, int_stub_177, int_stub_178, int_stub_179,
            int_stub_180, int_stub_181, int_stub_182, int_stub_183,
            int_stub_184, int_stub_185, int_stub_186, int_stub_187,
            int_stub_188, int_stub_189, int_stub_190, int_stub_191,
            int_stub_192, int_stub_193, int_stub_194, int_stub_195,
            int_stub_196, int_stub_197, int_stub_198, int_stub_199,
            int_stub_200, int_stub_201, int_stub_202, int_stub_203,
            int_stub_204, int_stub_205, int_stub_206, int_stub_207,
            int_stub_208, int_stub_209, int_stub_210, int_stub_211,
            int_stub_212, int_stub_213, int_stub_214, int_stub_215,
            int_stub_216, int_stub_217, int_stub_218, int_stub_219,
            int_stub_220, int_stub_221, int_stub_222, int_stub_223,
            int_stub_224, int_stub_225, int_stub_226, int_stub_227,
            int_stub_228, int_stub_229, int_stub_230, int_stub_231,
            int_stub_232, int_stub_233, int_stub_234, int_stub_235,
            int_stub_236, int_stub_237, int_stub_238, int_stub_239,
            int_stub_240, int_stub_241, int_stub_242, int_stub_243,
            int_stub_244, int_stub_245, int_stub_246, int_stub_247,
            int_stub_248, int_stub_249, int_stub_250, int_stub_251,
            int_stub_252, int_stub_253, int_stub_254, int_stub_255,
        ];

        // Fill in hardware IRQ vectors (32-255).
        //
        // IST selection (CRITICAL-013):
        //   Historically this used IST1 (an 8 KiB pre-allocated
        //   "kernel stacks we must not nest" stack) so that nested IRQs
        //   would not clobber the current kernel stack. In practice
        //   we have observed `vector=12 #SS` (`sel=0x0000`) faults at
        //   the very first `sti` executed after a successful disk
        //   read (e.g. right after `[SYS-RD] done` for csrss.exe):
        //   the IRQ push onto IST1 trips a stack-segment fault
        //   because the IST1 stack pointer or its backing memory is
        //   not in a state the CPU can dereference at that instant.
        //
        //   Workaround: switch the IRQ stubs to IST=0 so the CPU
        //   switches to the kernel's RSP0 (TSS.rsp0) on entry.
        //   `tss::set_rsp0(...)` is called from `enter_first_user_thread`
        //   and from `tss::set_rsp0_during_init`, both of which run
        //   early in `kernel_main`. Once the kernel is up, RSP0 is a
        //   valid kernel stack pointer so the IRQ pushes an iret
        //   frame onto a known-good stack. The cost is that nested
        //   IRQs share the kernel stack with the outer syscall, but
        //   the existing dispatcher is built for that already (it
        //   walks `[rsp+0x78]` directly). On the bring-up path we
        //   also keep interrupts MASKED in safe mode (PIC ports 0x21
        //   and 0xA1 are held at 0xFF), so even an IRQ firing
        //   during early boot would be silently dropped at the PIC
        //   before reaching the CPU.
        for (i, f) in irq_stubs.iter().enumerate() {
            IDT[32 + i] = GateDescriptor::interrupt(*f as u64, crate::arch::x86_64::gdt::KERNEL_CS, 0, 0);
        }

        let idt_ptr = IdtPtr {
            limit: (core::mem::size_of::<[GateDescriptor; 256]>() - 1) as u16,
            base: core::ptr::addr_of!(IDT) as u64,
        };
        asm!("lidt [{}]", in(reg) &idt_ptr, options(nostack));
    }
}

/// Wire a hardware vector to a Rust interrupt handler.
/// Hardware IRQs (PIC/APIC) use this to set up IRQ handlers.
pub fn install_irq(vector: u8, handler: u64) {
    set_gate(vector, handler, 0, 0);
}

#[allow(dead_code)]
pub fn _use_stub() {
    let _ = int_stub_0 as *const () as u64;
}
