//! Boot Video (bootvid.dll)
//
//! Implements the kernel's text-mode framebuffer used during
//! early boot. The real `bootvid.dll` in Windows NT 6.1 has two
//! responsibilities:
//
//! 1. Drive the legacy VGA text buffer (0xB8000) so kernel
//!    progress messages are visible to the user while the
//!    kernel-mode VDM is being set up.
//! 2. Provide a small bitmap interface for `Inbv`-style boot
//!    screens (the four-corner progress bar, the rotating
//!    spinner, the "Setup is loading..." banner).
//
//! In our environment we have two backends:
//
//! * The UEFI GOP linear framebuffer (preferred). winload
//!   publishes the LFB address, width, height, pitch, and
//!   format in `BootInfo.framebuffer_*`. We render into this
//!   memory once the kernel has mapped it (the bootloader
//!   already has it mapped).
//! * The legacy VGA text buffer at 0xB8000 (fallback). Used
//!   only when no GOP framebuffer is available.
//
//! BOOTVID itself is hardware-agnostic: the public API is the
//! same (`InbvDisplayString`, `InbvSetProgressBarSubset`,
//! `InbvRotateWaitingSpinner`, `VidCleanUp`, ...) and only the
//! pixel-write layer changes when the backend switches.
//
//! # Windows 7 Boot Display Modes
//
//! - Normal Boot: Static Windows logo, progress bar only (no scrolling logs)
//! - BootLog Mode: Minimal/no screen output, logs to ntbtlog.txt
//! - SOS Mode: Shows driver loading messages like "Loading \SystemRoot\..."

#![allow(non_snake_case)]

use core::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, AtomicU8, AtomicI32, Ordering};

/// Boot display mode (Windows 7 behavior)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BootDisplayMode {
    /// Normal boot - Windows logo, progress bar only (no scrolling logs)
    Normal,
    /// BootLog mode - minimal screen output, logging to ntbtlog.txt
    BootLog,
    /// SOS/Verbose mode - shows driver loading messages
    Sos,
}

impl Default for BootDisplayMode {
    fn default() -> Self {
        BootDisplayMode::Normal
    }
}

const VGA_TEXT_BASE: u64 = 0xB8000;
const VGA_COLS: u32 = 80;
const VGA_ROWS: u32 = 50;
const VGA_CELLS: usize = (VGA_COLS * VGA_ROWS) as usize;

/// Default text attributes used by the legacy VGA text buffer.
pub const ATTR_DEFAULT: u8 = 0x07; // light grey on black
pub const ATTR_HEADER:  u8 = 0x1F; // white on blue
pub const ATTR_BSOD:    u8 = 0x1F; // white on blue (Windows BSOD)

/// Cached description of the active framebuffer. Once
/// `init_from_framebuffer()` has been called we never go back
/// to the VGA path until `init()` is called explicitly.
static MODE_LFB: AtomicBool = AtomicBool::new(false);
static FB_BASE: AtomicU64 = AtomicU64::new(0);
static FB_WIDTH: AtomicU32 = AtomicU32::new(0);
static FB_HEIGHT: AtomicU32 = AtomicU32::new(0);
static FB_PITCH: AtomicU32 = AtomicU32::new(0);

/// Boot display mode - controls what is shown on screen
static BOOT_DISPLAY_MODE: AtomicI32 = AtomicI32::new(0);

/// Cursor and SPINNER state.
static INITIALISED: AtomicBool = AtomicBool::new(false);
static CURSOR_X: AtomicU32 = AtomicU32::new(0);
static CURSOR_Y: AtomicU32 = AtomicU32::new(0);
static SAVED_X: AtomicU32 = AtomicU32::new(0);
static SAVED_Y: AtomicU32 = AtomicU32::new(0);
static SPINNER_TICK: AtomicU32 = AtomicU32::new(0);
static ATTR: AtomicU8 = AtomicU8::new(ATTR_DEFAULT);

const SPINNER: [u8; 4] = [b'|', b'/', b'-', b'\\'];

/// 6x12 bitmap font for the LFB backend (each glyph is 6x12
/// pixels). The byte at index `c * 12 + r` is a column-major
/// bitmap for row `r` of glyph `c`. We use a minimal subset of
/// 96 printable ASCII glyphs; everything else renders as a
/// space. The actual font data is generated by `build_font`
/// below at compile time.
const FONT: [[u8; 12]; 96] = build_font();

const fn build_font() -> [[u8; 12]; 96] {
    // A subset of printable ASCII rendered as a 6x12 bitmap.
    // Each row is one byte. Bit 5 = leftmost, bit 0 = rightmost.
    // The font is hand-encoded below; missing glyphs render
    // as a blank. We include every letter, digit, and most
    // common punctuation so the progress bar / banner /
    // bugcheck strings all render correctly.
    const BLANK: [u8; 12] = [0,0,0,0,0,0,0,0,0,0,0,0];
    let mut f = [BLANK; 96];
    // Space
    f[b' ' as usize - 0x20] = BLANK;
    // !
    f[b'!' as usize - 0x20] = [0x04,0x04,0x04,0x04,0x04,0,0,0,0x04,0,0,0];
    // "
    f[b'"' as usize - 0x20] = [0x0A,0x0A,0x0A,0,0,0,0,0,0,0,0,0];
    // '
    f[b'\'' as usize - 0x20] = [0x04,0x04,0x08,0,0,0,0,0,0,0,0,0];
    // (
    f[b'(' as usize - 0x20] = [0x08,0x04,0x02,0x02,0x02,0x02,0x02,0x02,0x04,0x08,0,0];
    // )
    f[b')' as usize - 0x20] = [0x02,0x04,0x08,0x08,0x08,0x08,0x08,0x08,0x04,0x02,0,0];
    // *
    f[b'*' as usize - 0x20] = [0,0x0A,0x04,0x1F,0x04,0x0A,0,0,0,0,0,0];
    // +
    f[b'+' as usize - 0x20] = [0,0x04,0x04,0x1F,0x04,0x04,0,0,0,0,0,0];
    // ,
    f[b',' as usize - 0x20] = [0,0,0,0,0,0,0,0,0x04,0x04,0x08,0];
    // -
    f[b'-' as usize - 0x20] = [0,0,0,0,0x1F,0,0,0,0,0,0,0];
    // .
    f[b'.' as usize - 0x20] = [0,0,0,0,0,0,0,0,0x04,0x04,0,0];
    // /
    f[b'/' as usize - 0x20] = [0x08,0x08,0x04,0x04,0x02,0x02,0x01,0x01,0,0,0,0];
    // 0
    f[b'0' as usize - 0x20] = [0x0E,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x0E,0,0];
    // 1
    f[b'1' as usize - 0x20] = [0x04,0x06,0x05,0x04,0x04,0x04,0x04,0x04,0x04,0x0E,0,0];
    // 2
    f[b'2' as usize - 0x20] = [0x0E,0x11,0x10,0x10,0x08,0x04,0x02,0x01,0x01,0x1F,0,0];
    // 3
    f[b'3' as usize - 0x20] = [0x0E,0x11,0x10,0x10,0x0C,0x10,0x10,0x11,0x11,0x0E,0,0];
    // 4
    f[b'4' as usize - 0x20] = [0x08,0x08,0x0C,0x0A,0x0A,0x09,0x1F,0x08,0x08,0x1C,0,0];
    // 5
    f[b'5' as usize - 0x20] = [0x1F,0x01,0x01,0x0F,0x10,0x10,0x10,0x11,0x11,0x0E,0,0];
    // 6
    f[b'6' as usize - 0x20] = [0x0E,0x11,0x01,0x01,0x0F,0x11,0x11,0x11,0x11,0x0E,0,0];
    // 7
    f[b'7' as usize - 0x20] = [0x1F,0x10,0x08,0x08,0x04,0x04,0x02,0x02,0x02,0x02,0,0];
    // 8
    f[b'8' as usize - 0x20] = [0x0E,0x11,0x11,0x11,0x0E,0x11,0x11,0x11,0x11,0x0E,0,0];
    // 9
    f[b'9' as usize - 0x20] = [0x0E,0x11,0x11,0x11,0x11,0x1E,0x10,0x10,0x11,0x0E,0,0];
    // :
    f[b':' as usize - 0x20] = [0,0,0x04,0x04,0,0,0,0x04,0x04,0,0,0];
    // <
    f[b'<' as usize - 0x20] = [0x08,0x04,0x02,0x01,0x01,0x02,0x04,0x08,0,0,0,0];
    // =
    f[b'=' as usize - 0x20] = [0,0,0,0x1F,0,0x1F,0,0,0,0,0,0];
    // >
    f[b'>' as usize - 0x20] = [0x02,0x04,0x08,0x10,0x10,0x08,0x04,0x02,0,0,0,0];
    // ?
    f[b'?' as usize - 0x20] = [0x0E,0x11,0x10,0x10,0x08,0x04,0x04,0,0x04,0,0,0];
    // @
    f[b'@' as usize - 0x20] = [0x0E,0x11,0x10,0x16,0x15,0x15,0x16,0x10,0x11,0x0E,0,0];
    // A-Z
    f[b'A' as usize - 0x20] = [0x0E,0x11,0x11,0x11,0x11,0x1F,0x11,0x11,0x11,0x11,0,0];
    f[b'B' as usize - 0x20] = [0x0F,0x11,0x11,0x11,0x0F,0x11,0x11,0x11,0x11,0x0F,0,0];
    f[b'C' as usize - 0x20] = [0x0E,0x11,0x11,0x01,0x01,0x01,0x01,0x11,0x11,0x0E,0,0];
    f[b'D' as usize - 0x20] = [0x07,0x09,0x11,0x11,0x11,0x11,0x11,0x11,0x09,0x07,0,0];
    f[b'E' as usize - 0x20] = [0x1F,0x01,0x01,0x01,0x0F,0x01,0x01,0x01,0x01,0x1F,0,0];
    f[b'F' as usize - 0x20] = [0x1F,0x01,0x01,0x01,0x0F,0x01,0x01,0x01,0x01,0x01,0,0];
    f[b'G' as usize - 0x20] = [0x0E,0x11,0x11,0x01,0x1D,0x11,0x11,0x11,0x11,0x0E,0,0];
    f[b'H' as usize - 0x20] = [0x11,0x11,0x11,0x11,0x1F,0x11,0x11,0x11,0x11,0x11,0,0];
    f[b'I' as usize - 0x20] = [0x0E,0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x0E,0,0];
    f[b'J' as usize - 0x20] = [0x1E,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x09,0x06,0,0];
    f[b'K' as usize - 0x20] = [0x11,0x11,0x09,0x05,0x03,0x05,0x09,0x11,0x11,0x11,0,0];
    f[b'L' as usize - 0x20] = [0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x1F,0,0];
    f[b'M' as usize - 0x20] = [0x11,0x1B,0x15,0x15,0x15,0x11,0x11,0x11,0x11,0x11,0,0];
    f[b'N' as usize - 0x20] = [0x11,0x11,0x13,0x15,0x15,0x19,0x19,0x11,0x11,0x11,0,0];
    f[b'O' as usize - 0x20] = [0x0E,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x0E,0,0];
    f[b'P' as usize - 0x20] = [0x0F,0x11,0x11,0x11,0x0F,0x01,0x01,0x01,0x01,0x01,0,0];
    f[b'Q' as usize - 0x20] = [0x0E,0x11,0x11,0x11,0x11,0x11,0x15,0x09,0x0E,0x10,0,0];
    f[b'R' as usize - 0x20] = [0x0F,0x11,0x11,0x11,0x0F,0x05,0x09,0x11,0x11,0x11,0,0];
    f[b'S' as usize - 0x20] = [0x0E,0x11,0x01,0x01,0x0E,0x10,0x10,0x11,0x11,0x0E,0,0];
    f[b'T' as usize - 0x20] = [0x1F,0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,0,0];
    f[b'U' as usize - 0x20] = [0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x0E,0,0];
    f[b'V' as usize - 0x20] = [0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x0A,0x0A,0x04,0,0];
    f[b'W' as usize - 0x20] = [0x11,0x11,0x11,0x11,0x15,0x15,0x15,0x15,0x15,0x0A,0,0];
    f[b'X' as usize - 0x20] = [0x11,0x11,0x11,0x0A,0x04,0x0A,0x11,0x11,0x11,0x11,0,0];
    f[b'Y' as usize - 0x20] = [0x11,0x11,0x11,0x11,0x0A,0x04,0x04,0x04,0x04,0x04,0,0];
    f[b'Z' as usize - 0x20] = [0x1F,0x10,0x10,0x08,0x04,0x02,0x01,0x01,0x01,0x1F,0,0];
    // [
    f[b'[' as usize - 0x20] = [0x0E,0x02,0x02,0x02,0x02,0x02,0x02,0x02,0x02,0x0E,0,0];
    // \
    f[b'\\' as usize - 0x20] = [0x01,0x01,0x02,0x02,0x04,0x04,0x08,0x08,0x10,0x10,0,0];
    // ]
    f[b']' as usize - 0x20] = [0x0E,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x0E,0,0];
    // _
    f[b'_' as usize - 0x20] = [0,0,0,0,0,0,0,0,0,0x1F,0,0];
    // a-z (same shape as A-Z)
    f[b'a' as usize - 0x20] = f[b'A' as usize - 0x20];
    f[b'b' as usize - 0x20] = f[b'B' as usize - 0x20];
    f[b'c' as usize - 0x20] = f[b'C' as usize - 0x20];
    f[b'd' as usize - 0x20] = f[b'D' as usize - 0x20];
    f[b'e' as usize - 0x20] = f[b'E' as usize - 0x20];
    f[b'f' as usize - 0x20] = f[b'F' as usize - 0x20];
    f[b'g' as usize - 0x20] = f[b'G' as usize - 0x20];
    f[b'h' as usize - 0x20] = f[b'H' as usize - 0x20];
    f[b'i' as usize - 0x20] = f[b'I' as usize - 0x20];
    f[b'j' as usize - 0x20] = f[b'J' as usize - 0x20];
    f[b'k' as usize - 0x20] = f[b'K' as usize - 0x20];
    f[b'l' as usize - 0x20] = f[b'L' as usize - 0x20];
    f[b'm' as usize - 0x20] = f[b'M' as usize - 0x20];
    f[b'n' as usize - 0x20] = f[b'N' as usize - 0x20];
    f[b'o' as usize - 0x20] = f[b'O' as usize - 0x20];
    f[b'p' as usize - 0x20] = f[b'P' as usize - 0x20];
    f[b'q' as usize - 0x20] = f[b'Q' as usize - 0x20];
    f[b'r' as usize - 0x20] = f[b'R' as usize - 0x20];
    f[b's' as usize - 0x20] = f[b'S' as usize - 0x20];
    f[b't' as usize - 0x20] = f[b'T' as usize - 0x20];
    f[b'u' as usize - 0x20] = f[b'U' as usize - 0x20];
    f[b'v' as usize - 0x20] = f[b'V' as usize - 0x20];
    f[b'w' as usize - 0x20] = f[b'W' as usize - 0x20];
    f[b'x' as usize - 0x20] = f[b'X' as usize - 0x20];
    f[b'y' as usize - 0x20] = f[b'Y' as usize - 0x20];
    f[b'z' as usize - 0x20] = f[b'Z' as usize - 0x20];
    f
}

/// Initialise bootvid. If `init_from_framebuffer` was called
/// prior to this (the winload path) we render to the LFB.
/// Otherwise we fall back to the VGA text buffer.
pub fn init() {
    if INITIALISED.load(Ordering::Acquire) { return; }
    if MODE_LFB.load(Ordering::Acquire) {
        // Paint the loader blue across the whole framebuffer and
        // home the cursor at row 0 col 0.
        let base = FB_BASE.load(Ordering::Acquire);
        let width = FB_WIDTH.load(Ordering::Acquire);
        let height = FB_HEIGHT.load(Ordering::Acquire);
        let pitch = FB_PITCH.load(Ordering::Acquire);
        if base != 0 && width != 0 && height != 0 && pitch != 0 {
            // Loader blue (BGRA 0xD8 0x98 0x70) is already on
            // screen from the winload phase; the kernel
            // keeps the same colour but narrows the top status
            // area to a thin blue strip and leaves the bottom
            // for kernel logging.
            // No-op for now: cursor home only.
            CURSOR_X.store(0, Ordering::Release);
            CURSOR_Y.store(0, Ordering::Release);
            ATTR.store(0x1F, Ordering::Release);
            INITIALISED.store(true, Ordering::Release);
            return;
        }
    }
    // Legacy VGA path.
    VidInitialize();
}

/// Wire bootvid onto the winload-provided LFB. Call this from
/// `kernel_main` after the BOOTVID subsystem is selected as the
/// active display, but before any `InbvDisplayString` /
/// `paint_progress_bar` / `bugcheck_screen` calls.
pub fn init_from_framebuffer(base: u64, width: u32, height: u32, pitch: u32) {
    if base == 0 || width == 0 || height == 0 || pitch == 0 { return; }
    FB_BASE.store(base, Ordering::Release);
    FB_WIDTH.store(width, Ordering::Release);
    FB_HEIGHT.store(height, Ordering::Release);
    FB_PITCH.store(pitch, Ordering::Release);
    MODE_LFB.store(true, Ordering::Release);
    // We do NOT mark INITIALISED here so the public `init()`
    // call from `kernel_main` performs the cursor-home step.
}

/// One text-mode cell on the VGA path.
#[derive(Clone, Copy, Default)]
#[repr(C)]
struct TextCell {
    char: u8,
    attr: u8,
}

fn write_cell_vga(idx: usize, ch: u8, attr: u8) {
    let ptr = (VGA_TEXT_BASE as *mut u8).wrapping_add(idx * 2);
    unsafe {
        core::ptr::write_volatile(ptr, ch);
        core::ptr::write_volatile(ptr.add(1), attr);
    }
}

fn read_cell_vga(idx: usize) -> TextCell {
    let ptr = (VGA_TEXT_BASE as *const u8).wrapping_add(idx * 2);
    unsafe { TextCell { char: core::ptr::read_volatile(ptr), attr: core::ptr::read_volatile(ptr.add(1)) } }
}

fn scroll_up_vga() {
    for r in 1..VGA_ROWS as usize {
        for c in 0..VGA_COLS as usize {
            let src = read_cell_vga(r * VGA_COLS as usize + c);
            write_cell_vga((r - 1) * VGA_COLS as usize + c, src.char, src.attr);
        }
    }
    for c in 0..VGA_COLS as usize {
        write_cell_vga((VGA_ROWS as usize - 1) * VGA_COLS as usize + c, b' ', ATTR_DEFAULT);
    }
}

fn newline() {
    CURSOR_X.store(0, Ordering::Release);
    if MODE_LFB.load(Ordering::Acquire) {
        let y = CURSOR_Y.load(Ordering::Acquire) + 14;
        let h = FB_HEIGHT.load(Ordering::Acquire);
        if y + 14 > h { CURSOR_Y.store(h.saturating_sub(14), Ordering::Release); }
        else { CURSOR_Y.store(y, Ordering::Release); }
        return;
    }
    // Legacy VGA path.
    let y = CURSOR_Y.load(Ordering::Acquire) + 1;
    if y >= VGA_ROWS {
        scroll_up_vga();
        CURSOR_Y.store(VGA_ROWS - 1, Ordering::Release);
    } else {
        CURSOR_Y.store(y, Ordering::Release);
    }
}

/// Write a single ASCII character to the active console. The LFB
/// path uses the 6×12 bitmap font and updates `CURSOR_X`/
/// `CURSOR_Y`. The legacy path uses the 0xB8000 text buffer.
/// Always call this through the public surface (`InbvDisplayString`
/// or `put_byte_to_active_console`) so all callers see a single
/// code path.
fn putchar(ch: u8) {
    if MODE_LFB.load(Ordering::Acquire) {
        putchar_lfb(ch);
        return;
    }
    putchar_vga(ch);
}

/// Public wrapper for the per-byte console writer. Used by the
/// kernel's text-only paths (e.g. `gui_log` in `kernel_main` and
/// `rtl::klog::write_serial`) which already handle their own
/// `\n` / `\r` / `\t` semantics and just want to dump one byte
/// to whichever display is currently active. On the LFB path it
/// stays within the current `ATTR` colour pair.
///
/// This is an LFB-first API: in the winload → kernel boot path
/// the bootloader has already programmed the VGA controller to
/// scan out the linear framebuffer at the address supplied via
/// `BootInfo`, so writes to 0xB8000 are NOT visible. The bootvid
/// LFB backend is the only path that actually paints pixels
/// during that window.
pub fn put_byte_to_active_console(b: u8) {
    // Always publish what we render to the LFB path. Even when
    // the LFB hasn't been wired in yet, `MODE_LFB` is false and
    // we fall through to the legacy buffer.
    putchar(b);
}

/// True when the LFB backend is currently driving the display.
pub fn lfb_active() -> bool {
    MODE_LFB.load(Ordering::Acquire)
}

/// Force the bootvid putchar / cursor logic onto the LFB
/// backend. Used by `gui_log::init()` once the kernel has
/// transitioned from UEFI GOP to the VGA text-mode console:
/// QEMU's `-display gtk` window keeps scanning the GOP LFB
/// until it is told otherwise, so the only way to make the
/// user's GUI window show the kernel's CMD prompt is to
/// render every cell into the LFB as well.
///
/// Safe to call before `init_from_framebuffer`; if the LFB
/// wasn't wired in (no `BootInfo.framebuffer_*` reported by
/// winload) the putchar path will silently no-op because
/// `FB_BASE` / `FB_PITCH` stay zero.
pub fn force_lfb_console() {
    let base = FB_BASE.load(Ordering::Acquire);
    if base == 0 { return; }
    MODE_LFB.store(true, Ordering::Release);
}

fn putchar_vga(ch: u8) {
    match ch {
        b'\n' => { newline(); return; }
        b'\r' => { CURSOR_X.store(0, Ordering::Release); return; }
        b'\t' => {
            let x = CURSOR_X.load(Ordering::Acquire);
            let next = (x / 8 + 1) * 8;
            CURSOR_X.store(next, Ordering::Release);
            if CURSOR_X.load(Ordering::Acquire) >= VGA_COLS { newline(); }
            return;
        }
        0x08 => {
            let x = CURSOR_X.load(Ordering::Acquire);
            if x > 0 { CURSOR_X.store(x - 1, Ordering::Release); }
            let y = CURSOR_Y.load(Ordering::Acquire);
            write_cell_vga(y as usize * VGA_COLS as usize + CURSOR_X.load(Ordering::Acquire) as usize, b' ', ATTR_DEFAULT);
            return;
        }
        _ => {}
    }
    let x = CURSOR_X.load(Ordering::Acquire);
    let y = CURSOR_Y.load(Ordering::Acquire);
    let attr = ATTR.load(Ordering::Acquire);
    write_cell_vga(y as usize * VGA_COLS as usize + x as usize, ch, attr);
    let nx = x + 1;
    if nx >= VGA_COLS { newline(); } else { CURSOR_X.store(nx, Ordering::Release); }
}

/// Draw the ascii glyph for `ch` at the current cursor position
/// on the LFB backend. We use 6×12 pixel glyphs from `FONT`.
fn putchar_lfb(ch: u8) {
    match ch {
        b'\n' => { newline(); return; }
        b'\r' => { CURSOR_X.store(0, Ordering::Release); return; }
        b'\t' => {
            let x = CURSOR_X.load(Ordering::Acquire);
            let next = x + 8 * 6;
            CURSOR_X.store(next, Ordering::Release);
            return;
        }
        0x08 => {
            let x = CURSOR_X.load(Ordering::Acquire);
            if x > 0 { CURSOR_X.store(x - 6, Ordering::Release); }
            return;
        }
        _ => {}
    }
    let glyph_idx = if ch >= 0x20 && ch < 0x80 {
        (ch - 0x20) as usize
    } else {
        0  // map to space
    };
    let base = FB_BASE.load(Ordering::Acquire);
    let pitch = FB_PITCH.load(Ordering::Acquire);
    let height = FB_HEIGHT.load(Ordering::Acquire);
    let width = FB_WIDTH.load(Ordering::Acquire);
    let mut px = CURSOR_X.load(Ordering::Acquire);
    let py = CURSOR_Y.load(Ordering::Acquire);
    if base == 0 || pitch == 0 { return; }
    let attr = ATTR.load(Ordering::Acquire);
    let fg = colour_for_attr(attr);
    let bg = colour_for_attr(attr >> 4);
    let glyph = &FONT[glyph_idx];
    for row in 0..12u32 {
        let bits = glyph[row as usize];
        for col in 0..6u32 {
            // Fix X-axis mirror: use bit 0 for leftmost pixel (original used bit 5)
            let on = (bits >> col) & 1 != 0;
            let x = px + col;
            let y = py + row;
            if x >= width || y >= height { continue; }
            let off = (y * pitch + x * 4) as usize;
            unsafe {
                let p = (base as *mut u8).add(off);
                let pix = if on { fg } else { bg };
                core::ptr::write_volatile(p, pix[0]);      // B
                core::ptr::write_volatile(p.add(1), pix[1]); // G
                core::ptr::write_volatile(p.add(2), pix[2]); // R
                core::ptr::write_volatile(p.add(3), pix[3]); // A
            }
        }
    }
    px = px + 6;
    if px + 6 > width { newline(); }
    else { CURSOR_X.store(px, Ordering::Release); }
    let _ = attr; // silence unused
}

/// Map a 4-bit VGA attribute (low nibble = fg) to a 4-byte BGRA
/// pixel. We use the canonical Windows 7 console palette. Each entry
/// is `[B, G, R, A]` because the LFB is scanned out in BGRA order
/// (matches the OVMF GOP `PixelFormat::Bgr`). Note in particular:
///   * index 1 (dark blue)  → R=0x00, G=0x00, B=0xAA — a TRUE dark blue,
///     NOT dark red (which was the bug in earlier builds, where the
///     table stored `[0xAA,0,0]` which QEMU scanned out as B=0xAA so
///     the blue console title bar came out red).
///   * index 4 (dark red)   → R=0xAA, G=0x00, B=0x00 — a TRUE dark red.
fn colour_for_attr(idx: u8) -> [u8; 4] {
    match idx & 0x0F {
        0 => [0x00, 0x00, 0x00, 0xFF], // black
        1 => [0xAA, 0x00, 0x00, 0xFF], // dark blue   (B=0xAA, R=0x00)
        2 => [0x00, 0xAA, 0x00, 0xFF], // dark green  (G=0xAA)
        3 => [0xAA, 0xAA, 0x00, 0xFF], // dark cyan   (B=0xAA, G=0xAA)
        4 => [0x00, 0x00, 0xAA, 0xFF], // dark red    (R=0xAA)
        5 => [0xAA, 0x00, 0xAA, 0xFF], // dark magenta
        6 => [0x00, 0x55, 0xAA, 0xFF], // dark yellow / brown
        7 => [0xAA, 0xAA, 0xAA, 0xFF], // light grey
        8 => [0x55, 0x55, 0x55, 0xFF], // dark grey
        9 => [0xFF, 0x55, 0x55, 0xFF], // light blue
       10 => [0x55, 0xFF, 0x55, 0xFF], // light green
       11 => [0xFF, 0xFF, 0x55, 0xFF], // light cyan
       12 => [0x55, 0x55, 0xFF, 0xFF], // light red
       13 => [0xFF, 0x55, 0xFF, 0xFF], // light magenta
       14 => [0x55, 0xFF, 0xFF, 0xFF], // yellow
       15 => [0xFF, 0xFF, 0xFF, 0xFF], // white
        _ => [0xFF, 0xFF, 0xFF, 0xFF],
    }
}

/// `InbvDisplayString` — write a NUL-terminated ASCII string.
pub fn InbvDisplayString(s: &[u8]) {
    for &b in s {
        if b == 0 { break; }
        putchar(b);
    }
}

/// NUL-terminated display, attribute can be supplied by the caller.
pub fn VidDisplayString(s: &[u8], attr: u8) {
    for &b in s {
        if b == 0 { break; }
        if b == b'\n' { newline(); continue; }
        ATTR.store(attr, Ordering::Release);
        putchar(b);
    }
    ATTR.store(ATTR_DEFAULT, Ordering::Release);
}

/// Same as above but also flushes any pending display operations
/// (no-op in our environment because the serial line is the same
/// one the kernel prints to).
pub fn InbvDisplayStringBlocking(s: &[u8]) {
    InbvDisplayString(s);
}

/// `InbvSetProgressBarSubset` — display `count` filled blocks.
pub fn InbvSetProgressBarSubset(count: u32) {
    if !INITIALISED.load(Ordering::Acquire) { return; }
    if MODE_LFB.load(Ordering::Acquire) {
        // On the LFB we paint a 24-pixel-tall horizontal bar near
        // the bottom of the framebuffer. Colours are BGRA byte
        // triplets: byte 0 = B, byte 1 = G, byte 2 = R.
        let bar_h = 24u32;
        let bar_y0 = FB_HEIGHT.load(Ordering::Acquire).saturating_sub(bar_h + 8);
        let width = FB_WIDTH.load(Ordering::Acquire);
        let base = FB_BASE.load(Ordering::Acquire);
        let pitch = FB_PITCH.load(Ordering::Acquire);
        let total = (width / 6).max(1);
        let filled = (count as u32).min(total);
        // Empty bar (dark grey on black).
        for row in 0..bar_h {
            for col in 0..width {
                let off = ((bar_y0 + row) * pitch + col * 4) as usize;
                unsafe {
                    let p = (base as *mut u8).add(off);
                    core::ptr::write_volatile(p,     0x40); // B
                    core::ptr::write_volatile(p.add(1), 0x40); // G
                    core::ptr::write_volatile(p.add(2), 0x40); // R
                    core::ptr::write_volatile(p.add(3), 0xFF);
                }
            }
        }
        // Filled segment (bright yellow: high R, high G, low B).
        let fill_w = filled * 6;
        for row in 0..bar_h {
            for col in 0..fill_w {
                let off = ((bar_y0 + row) * pitch + col * 4) as usize;
                unsafe {
                    let p = (base as *mut u8).add(off);
                    core::ptr::write_volatile(p,     0x00); // B
                    core::ptr::write_volatile(p.add(1), 0xFF); // G
                    core::ptr::write_volatile(p.add(2), 0xFF); // R
                    core::ptr::write_volatile(p.add(3), 0xFF);
                }
            }
        }
        return;
    }
    // VGA path.
    SAVED_X.store(CURSOR_X.load(Ordering::Acquire), Ordering::Release);
    SAVED_Y.store(CURSOR_Y.load(Ordering::Acquire), Ordering::Release);
    CURSOR_X.store(0, Ordering::Release);
    CURSOR_Y.store(VGA_ROWS - 1, Ordering::Release);
    let blocks = (count as u32).min(VGA_COLS);
    for c in 0..VGA_COLS as usize {
        let ch = if (c as u32) < blocks { 0xDB } else { 0xB0 };
        write_cell_vga((VGA_ROWS as usize - 1) * VGA_COLS as usize + c, ch, ATTR_HEADER);
    }
    CURSOR_X.store(SAVED_X.load(Ordering::Acquire), Ordering::Release);
    CURSOR_Y.store(SAVED_Y.load(Ordering::Acquire), Ordering::Release);
}

/// `InbvRotateWaitingSpinner` — show the four-frame spinner.
pub fn InbvRotateWaitingSpinner() {
    if !INITIALISED.load(Ordering::Acquire) { return; }
    let tick = SPINNER_TICK.fetch_add(1, Ordering::Relaxed);
    let frame = SPINNER[(tick as usize) & 3];
    putchar(frame);
}

/// `VidResetDisplay` — clear and rehome.
pub fn VidResetDisplay(bios: bool) {
    let _ = bios;
    if MODE_LFB.load(Ordering::Acquire) {
        // Paint the entire framebuffer solid BLACK. We deliberately
        // do NOT use the loader-blue (`0xD8, 0x98, 0x70`) that bootmgr
        // and winload leave on screen — that colour was chosen by the
        // Windows 7 boot-manager UI team and only makes sense against
        // a black wallpaper with white text. The kernel's own boot
        // screen uses white-on-black, so we wipe the framebuffer to
        // black here and let `paint_phase_banner` (if called) draw
        // whatever top stripe the caller wants. Black (`0x00, 0x00,
        // 0x00, 0xFF` in BGRA) keeps the LFB in sync with the legacy
        // 0xB8000 text console that `gui_log::init()` also clears to
        // attribute 0x07 (light grey on black).
        let base = FB_BASE.load(Ordering::Acquire);
        let pitch = FB_PITCH.load(Ordering::Acquire);
        let width = FB_WIDTH.load(Ordering::Acquire);
        let height = FB_HEIGHT.load(Ordering::Acquire);
        if base != 0 && pitch != 0 && width != 0 && height != 0 {
            let total_bytes = (pitch as usize) * (height as usize);
            unsafe {
                let p = base as *mut u8;
                let mut off = 0usize;
                while off + 4 <= total_bytes {
                    core::ptr::write_volatile(p.add(off),     0x00);
                    core::ptr::write_volatile(p.add(off + 1), 0x00);
                    core::ptr::write_volatile(p.add(off + 2), 0x00);
                    core::ptr::write_volatile(p.add(off + 3), 0xFF);
                    off += 4;
                }
            }
        }
        CURSOR_X.store(0, Ordering::Release);
        CURSOR_Y.store(0, Ordering::Release);
        return;
    }
    for i in 0..VGA_CELLS {
        write_cell_vga(i, b' ', ATTR_DEFAULT);
    }
    CURSOR_X.store(0, Ordering::Release);
    CURSOR_Y.store(0, Ordering::Release);
}

/// `VidCleanUp` — disable the cursor and leave the screen alone.
pub fn VidCleanUp() {
    if !INITIALISED.load(Ordering::Acquire) { return; }
    // No-op for the LFB path. On the VGA path this would disable
    // the cursor via the CRTC index port, which is unsafe in
    // long mode.
}

/// `VidClearBlack` — paint the entire LFB solid black. Used
/// when transitioning from the UEFI GOP loader screen (which
/// leaves a blue/grey panel) to the kernel's VGA text mode
/// (which renders black-on-white). QEMU's `-display gtk`
/// keeps scanning out the GOP LFB until the user re-opens
/// the window, so we have to overwrite the stale pixels
/// before we start drawing text on top of them.
pub fn VidClearBlack() {
    if !MODE_LFB.load(Ordering::Acquire) { return; }
    let base   = FB_BASE.load(Ordering::Acquire);
    let pitch  = FB_PITCH.load(Ordering::Acquire);
    let width  = FB_WIDTH.load(Ordering::Acquire);
    let height = FB_HEIGHT.load(Ordering::Acquire);
    if base == 0 || pitch == 0 || width == 0 || height == 0 { return; }
    let total_bytes = (pitch as usize) * (height as usize);
    unsafe {
        let p = base as *mut u8;
        let mut off = 0usize;
        while off + 4 <= total_bytes {
            core::ptr::write_volatile(p.add(off),     0x00);
            core::ptr::write_volatile(p.add(off + 1), 0x00);
            core::ptr::write_volatile(p.add(off + 2), 0x00);
            core::ptr::write_volatile(p.add(off + 3), 0xFF);
            off += 4;
        }
    }
    CURSOR_X.store(0, Ordering::Release);
    CURSOR_Y.store(0, Ordering::Release);
}

/// `VidSetCursorPosition` — programmatic cursor placement.
pub fn VidSetCursorPosition(x: u16, y: u16) {
    CURSOR_X.store(x as u32, Ordering::Release);
    CURSOR_Y.store(y as u32, Ordering::Release);
}

/// Read the current bootvid cursor coordinates. Used by
/// callers that want to position a glyph without disturbing
/// the natural cursor flow (e.g. the Safe-Mode console
/// layout paint routine in `hal::x86_64::text_console`).
pub fn cursor_position() -> (u16, u16) {
    (
        CURSOR_X.load(Ordering::Acquire) as u16,
        CURSOR_Y.load(Ordering::Acquire) as u16,
    )
}

/// Snapshot of the wired-in linear framebuffer (base, width,
/// height, pitch). Useful for diagnostics — `show_safe_mode_console`
/// logs these so an operator can confirm the LFB is alive when
/// the Safe-Mode console is painted.
pub fn lfb_info() -> (u64, u32, u32, u32) {
    (
        FB_BASE.load(Ordering::Acquire),
        FB_WIDTH.load(Ordering::Acquire),
        FB_HEIGHT.load(Ordering::Acquire),
        FB_PITCH.load(Ordering::Acquire),
    )
}

#[inline]
pub fn fb_base() -> u64 { FB_BASE.load(Ordering::Acquire) }
#[inline]
pub fn fb_width() -> u32 { FB_WIDTH.load(Ordering::Acquire) }
#[inline]
pub fn fb_height() -> u32 { FB_HEIGHT.load(Ordering::Acquire) }

/// Pick the text attribute used by the next characters. Standard
/// 16-colour VGA palette (see `colour_for_attr`).
pub fn set_attr(attr: u8) {
    ATTR.store(attr, Ordering::Release);
}

pub fn get_attr() -> u8 { ATTR.load(Ordering::Acquire) }

/// `VidInitialize` — clear the screen, home the cursor. VGA path only.
pub fn VidInitialize() {
    if INITIALISED.load(Ordering::Acquire) { return; }
    // Skip VGA clear — 0xB8000 may be RO after ExitBootServices
    // (UEFI page tables don't identity-map it).
    CURSOR_X.store(0, Ordering::Release);
    CURSOR_Y.store(0, Ordering::Release);
    INITIALISED.store(true, Ordering::Release);
    ATTR.store(ATTR_DEFAULT, Ordering::Release);
}

/// Phase banner: paint a coloured top strip with the supplied title,
/// then clear the rest of the screen. Used by the BOOTVID glue
/// in `kernel_main` to draw a Windows-style progress banner.
///
/// NOTE: We previously painted the top 48 rows with the loader blue
/// (`0xD8, 0x98, 0x70`) — that was the original Win7 bootmgr screen
/// but it does not match the kernel's white-on-black console that
/// `gui_log` brings up afterwards. We now keep the entire framebuffer
/// black (the `VidResetDisplay` call above already wiped it) and
/// only paint the title text. The banner therefore reads as white
/// "Windows 7" centred in the top quarter of a black screen, which
/// is what the kernel user sees during the normal boot sequence.
pub fn paint_phase_banner(title: &str) {
    if !MODE_LFB.load(Ordering::Acquire) { return; }
    VidResetDisplay(true);
    let base = FB_BASE.load(Ordering::Acquire);
    let pitch = FB_PITCH.load(Ordering::Acquire);
    let width = FB_WIDTH.load(Ordering::Acquire);
    let height = FB_HEIGHT.load(Ordering::Acquire);
    if base == 0 || pitch == 0 { return; }
    let _ = base; let _ = pitch; let _ = height; // silence unused
    // Title text in WHITE on BLACK. We use the same 6×12 font. The
    // default attribute `ATTR_DEFAULT` (0x07 = light grey on black)
    // was previously swapped to 0x1F (white on blue) so the title
    // would be visible on the loader-blue top stripe; with the
    // stripe gone we want white text on the existing black BGRA
    // pixels and ATTR 0x0F (white on black) is the right value.
    let title_w_px = (title.len() as u32) * 6;
    let x0 = if width > title_w_px { (width - title_w_px) / 2 } else { 0 };
    let y0 = (height / 4).saturating_sub(6);
    CURSOR_X.store(x0, Ordering::Release);
    CURSOR_Y.store(y0, Ordering::Release);
    let prev_attr = ATTR.swap(0x0F, Ordering::AcqRel);
    InbvDisplayString(title.as_bytes());
    ATTR.store(prev_attr, Ordering::Release);
    CURSOR_X.store(0, Ordering::Release);
    CURSOR_Y.store(y0 + 24, Ordering::Release);
}

/// Paint a bottom progress-bar segment representing `percent`% of
/// `100` (clamped to `[0, 100]`). Used by `kernel_main` between
/// phases.
pub fn paint_progress_bar(percent: u32) {
    InbvSetProgressBarSubset(percent);
}

/// Paint the Windows-style BSOD. `code` is the bugcheck code
/// formatted as 8 hex digits, `secondary` is the optional
/// secondary status line.
pub fn bugcheck_screen(code: u32, secondary: &str) {
    if MODE_LFB.load(Ordering::Acquire) {
        VidResetDisplay(true);
        // Cover the entire screen in 0x0012_90_78 (BGRA) — the
        // canonical Win7 BSOD background.
        let base = FB_BASE.load(Ordering::Acquire);
        let pitch = FB_PITCH.load(Ordering::Acquire);
        let width = FB_WIDTH.load(Ordering::Acquire);
        let height = FB_HEIGHT.load(Ordering::Acquire);
        if base == 0 || pitch == 0 { return; }
        for y in 0..height {
            for x in 0..width {
                let off = (y * pitch + x * 4) as usize;
                unsafe {
                    let p = (base as *mut u8).add(off);
                    core::ptr::write_volatile(p, 0x90);
                    core::ptr::write_volatile(p.add(1), 0x12);
                    core::ptr::write_volatile(p.add(2), 0x00);
                    core::ptr::write_volatile(p.add(3), 0xFF);
                }
            }
        }
        // Title in 0x1F (white on blue attribute semantically, but
        // we render pure white on the blue background).
        CURSOR_X.store((width / 4).max(8), Ordering::Release);
        CURSOR_Y.store(height / 4, Ordering::Release);
        ATTR.store(0x1F, Ordering::Release);
        // Use a small scratch buffer to format a diagnostic header so the
        // `hex_buf` value is actually consumed by the call site below.
        let mut hex_buf = [0u8; 16];
        let hex_prefix = b"*** STOP: 0x";
        hex_buf[..hex_prefix.len()].copy_from_slice(hex_prefix);
        InbvDisplayString(&hex_buf[..hex_prefix.len()]);
        let code_str = format_hex(code);
        InbvDisplayString(&code_str);
        InbvDisplayString(b"\n\n");
        ATTR.store(0x0E, Ordering::Release);
        InbvDisplayString(secondary.as_bytes());
        return;
    }

    // VGA fallback: write to the text buffer.
    VidInitialize();
    InbvDisplayString(b"*** STOP: 0x");
    let code_str = format_hex(code);
    InbvDisplayString(&code_str);
    InbvDisplayString(b"\n\n");
    InbvDisplayString(secondary.as_bytes());
}

fn format_hex(v: u32) -> [u8; 10] {
    let hex = b"0123456789ABCDEF";
    let mut out = [0u8; 10];
    for i in 0..8 {
        let nib = ((v >> ((7 - i) * 4)) & 0xF) as usize;
        out[i] = hex[nib];
    }
    out[8] = b' ';
    out[9] = b' ';
    out
}

// ============================================================================
// Windows 7 Boot Display Mode Control
// ============================================================================

impl BootDisplayMode {
    /// Get boot display mode from atomic value
    pub fn from_atomic() -> Self {
        match BOOT_DISPLAY_MODE.load(Ordering::Acquire) {
            0 => BootDisplayMode::Normal,
            1 => BootDisplayMode::BootLog,
            2 => BootDisplayMode::Sos,
            _ => BootDisplayMode::Normal,
        }
    }
    
    /// Set boot display mode
    pub fn set(mode: BootDisplayMode) {
        match mode {
            BootDisplayMode::Normal => BOOT_DISPLAY_MODE.store(0, Ordering::Release),
            BootDisplayMode::BootLog => BOOT_DISPLAY_MODE.store(1, Ordering::Release),
            BootDisplayMode::Sos => BOOT_DISPLAY_MODE.store(2, Ordering::Release),
        }
    }
}

/// Set the boot display mode (called from kernel_main based on boot options)
pub fn set_boot_mode(mode: BootDisplayMode) {
    BootDisplayMode::set(mode);
}

/// Get current boot display mode
pub fn get_boot_mode() -> BootDisplayMode {
    BootDisplayMode::from_atomic()
}

/// Check if we should display scrolling text (SOS mode only)
fn should_display_scrolling() -> bool {
    BootDisplayMode::from_atomic() == BootDisplayMode::Sos
}

/// Display a message on screen (respects boot mode)
/// - Normal: Only progress bar updates
/// - BootLog: Minimal/no output
/// - SOS: Show driver loading messages
pub fn display_boot_message(msg: &[u8]) {
    let mode = BootDisplayMode::from_atomic();
    
    match mode {
        BootDisplayMode::Normal => {
            // Normal mode: Don't display scrolling text, only update progress bar
            // This matches Windows 7 behavior where you see the logo and progress bar
        }
        BootDisplayMode::BootLog => {
            // BootLog mode: Minimal output, logging goes to ntbtlog.txt
        }
        BootDisplayMode::Sos => {
            // SOS mode: Display driver loading messages
            InbvDisplayString(msg);
        }
    }
}

/// Display SOS-style driver loading message
/// Format: "Loading \SystemRoot\system32\file.sys"
pub fn display_sos_loading(driver_path: &[u8]) {
    if !should_display_scrolling() {
        return;
    }
    
    // Format: "Loading \SystemRoot\..."
    let prefix = b"Loading ";
    for &b in prefix {
        putchar(b);
    }
    InbvDisplayString(driver_path);
}

/// Display Windows 7 logo screen (normal boot)
pub fn display_windows_logo() {
    // In normal boot mode, display the Windows 7 loading screen
    // The logo is displayed during boot, not scrolling text
    paint_phase_banner("Windows 7");
    
    // Set up progress bar area
    paint_progress_bar(0);
}

/// Update boot progress (0-100)
pub fn update_progress(percent: u32) {
    paint_progress_bar(percent);
}

/// Smoke test for bootvid
pub fn smoke_test() -> bool {
    init();
    InbvDisplayString(b"BootVid Smoke Test:\n");
    InbvDisplayString(b"  Hello, kernel!\n");
    for _ in 0..4 { InbvRotateWaitingSpinner(); }
    InbvSetProgressBarSubset(40);
    InbvDisplayString(b"\n");
    VidCleanUp();
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn font_includes_printable_glyphs() {
        assert!(FONT[b'A' as usize - 0x20][0] != 0);
        assert!(FONT[b'0' as usize - 0x20][0] != 0);
        assert_eq!(FONT[b' ' as usize - 0x20][0], 0);
    }
    
    #[test]
    fn boot_display_mode_default() {
        assert_eq!(get_boot_mode(), BootDisplayMode::Normal);
    }
}
