//! `cmd-stub-gen` — Rust port of `tools/cmd-stub-gen/cmd_asm.py` and
//! `all_stubs.py`. Produces the same four `pub const` arrays the kernel
//! build bakes into `boot_stubs.rs`.
//!
//! Run with no arguments to regenerate
//! `nt61/tools/src/fs/stubs/boot_stubs.rs` next to this crate, or pass
//! an explicit output path as `argv[1]`.
//!
//! Example:
//!     cargo run --manifest-path nt61/tools/cmd-stub-gen/Cargo.toml \
//!         --release -- nt61/tools/src/fs/stubs/boot_stubs.rs

use std::fs;
use std::path::PathBuf;

mod codegen;
mod cmd;
mod strings;
mod stubs;

use strings::{
    CMD_STUB_SIZE, LSM_STUB_SIZE, USERINIT_STUB_SIZE, WINLOGON_STUB_SIZE,
};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let output_path = args
        .get(1)
        .cloned()
        .unwrap_or_else(|| String::from("../src/fs/stubs/boot_stubs.rs"));

    let cmd_bytes = cmd::build();
    assert_eq!(cmd_bytes.len(), CMD_STUB_SIZE);
    let lsm_bytes = stubs::build_lsm();
    assert_eq!(lsm_bytes.len(), LSM_STUB_SIZE);
    let winlogon_bytes = stubs::build_winlogon();
    assert_eq!(winlogon_bytes.len(), WINLOGON_STUB_SIZE);
    let userinit_bytes = stubs::build_userinit();
    assert_eq!(userinit_bytes.len(), USERINIT_STUB_SIZE);

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by nt61/tools/cmd-stub-gen (Rust port).\n");
    out.push_str("// DO NOT EDIT BY HAND. Re-run the generator after editing\n");
    out.push_str("// the stub emitters.\n\n");
    out.push_str(&emit_array("CMD_EXE_TEXT_STUB", &cmd_bytes));
    out.push('\n');
    out.push_str(&emit_array("LSM_EXE_TEXT_STUB", &lsm_bytes));
    out.push('\n');
    out.push_str(&emit_array("WINLOGON_EXE_TEXT_STUB", &winlogon_bytes));
    out.push('\n');
    out.push_str(&emit_array("USERINIT_EXE_TEXT_STUB", &userinit_bytes));

    let path = PathBuf::from(&output_path);
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).expect("create output directory");
        }
    }
    fs::write(&path, &out).expect("write boot_stubs.rs");
    println!("Wrote {} ({} bytes total)", output_path, out.len());
}

fn emit_array(name: &str, bytes: &[u8]) -> String {
    let mut s = String::new();
    s.push_str(&format!("pub const {}: [u8; {}] = [\n", name, bytes.len()));
    for (i, chunk) in bytes.chunks(16).enumerate() {
        if i > 0 {
            s.push_str(",\n");
        }
        s.push_str("    ");
        let parts: Vec<String> = chunk.iter().map(|b| format!("0x{:02x}", b)).collect();
        s.push_str(&parts.join(", "));
    }
    s.push_str(",\n];\n");
    s
}
